### ISSUE TITLE
Fastimage raises on broken JPG

### ISSUE THREAD

**Issue by fschwahn** [sdsykes/fastimage#152]
We have a file (I unfortunately cannot share) which causes fastimage to raise the following error:

```
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastimage-2.3.0/lib/fastimage.rb:518:in `skip': undefined method `size' for #<Net::ReadAdapter> (NoMethodError)

        fetched += new_string.size
                             ^^^^^
```

and the following backtrace:

```
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastimage-2.3.0/lib/fastimage.rb:518:in `skip'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastimage-2.3.0/lib/fastimage.rb:879:in `block in parse_size_for_jpeg'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastimage-2.3.0/lib/fastimage.rb:849:in `loop'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastimage-2.3.0/lib/fastimage.rb:849:in `parse_size_for_jpeg'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastimage-2.3.0/lib/fastimage.rb:434:in `parse_size'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastimage-2.3.0/lib/fastimage.rb:414:in `parse_packets'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastimage-2.3.0/lib/fastimage.rb:341:in `block in fetch_using_http_from_parsed_uri'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/3.2.0/net/http.rb:2353:in `block in transport_request'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/3.2.0/net/http/response.rb:320:in `reading_body'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/3.2.0/net/http.rb:2352:in `transport_request'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/3.2.0/net/http.rb:2306:in `request'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/3.2.0/net/http.rb:2299:in `block in request'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/3.2.0/net/http.rb:1570:in `start'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/3.2.0/net/http.rb:2297:in `request'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/3.2.0/net/http.rb:2177:in `request_get'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastimage-2.3.0/lib/fastimage.rb:301:in `fetch_using_http_from_parsed_uri'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastimage-2.3.0/lib/fastimage.rb:283:in `fetch_using_http'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastimage-2.3.0/lib/fastimage.rb:249:in `initialize'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastimage-2.3.0/lib/fastimage.rb:143:in `new'
/Users/fabian/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastimage-2.3.0/lib/fastimage.rb:143:in `size'
```

I found the following line https://github.com/sdsykes/fastimage/blob/f832581881feabe8e060968d2c842f16368ae98b/lib/fastimage.rb#L487 which was introduced in 437318220b847a914661dada71ef34afd905d1d2 . This commit was added to fix an issue with webmock, but I'm not using webmock, this also happens when I start a plain `irb` session and require only `fastimage`.

Anyway, adding the same line in the `skip`-method (at line 512) here https://github.com/sdsykes/fastimage/blob/f832581881feabe8e060968d2c842f16368ae98b/lib/fastimage.rb#L509-L519

fixes the problem - fastimage no longer raises.

I have no idea what this actually does, so I'm not sure it's a proper fix, but it prevents the error from raising. Maybe also
```ruby
raise CannotParseImage if !new_string || new_string.is_a? Net::ReadAdapter
```

would be the right thing to do here.

**Comment by sdsykes** [comment]
Surely this is a bug in Net::HTTP. I would love to be able to reproduce this, Net::ReadAdapter is an internal class that shouldn't leak outside of Net::HTTP as far as I can see.
Is there anything more about the circumstances of this bug you can share?

**Comment by fschwahn** [comment]
Sorry, nothing else. 

It reproduced consistently with the offending image, and the image file was damaged.

**Comment by sdsykes** [comment]
Ah no worries, I managed to reproduce, it's because actually the Fiber terminates and just returns whatever, I will fix this correctly shortly.

**Comment by fschwahn** [comment]
Great to hear that!
