### ISSUE TITLE
Problem using fastimage in heroku using ssl

### ISSUE THREAD

**Issue by luccasmaso** [sdsykes/fastimage#47]
I found a crash when running `FastImage.size(src)` with this particular url "https://pixel.quantserve.com/pixel/p-9tnwrxnK1azF1.gif" in production.

In my localhost the execution returns [1, 1] array ok. But I noticed that in the heroku production environment it throws an ssl exception:

```
irb(main):002:0> FastImage.size("https://pixel.quantserve.com/pixel/p-9tnwrxnK1azF1.gif")
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:918:in `connect'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:918:in `connect'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:1278:in `request_get'
	from /app/vendor/bundle/ruby/2.0.0/gems/fastimage-1.6.3/lib/fastimage.rb:212:in `fetch_using_http_from_parsed_uri'
	from /app/vendor/bundle/ruby/2.0.0/gems/fastimage-1.6.3/lib/fastimage.rb:207:in `fetch_using_http'
	from /app/vendor/bundle/ruby/2.0.0/gems/fastimage-1.6.3/lib/fastimage.rb:173:in `initialize'
	from /app/vendor/bundle/ruby/2.0.0/gems/fastimage-1.6.3/lib/fastimage.rb:114:in `new'
	from /app/vendor/bundle/ruby/2.0.0/gems/fastimage-1.6.3/lib/fastimage.rb:114:in `size'
```

What should I do? It's something that can be changed in the fastimage code or some configuration on the server side?

Thanks

**Comment by sdsykes** [comment]
I don't know - perhaps heroku support could throw some light on why net/http can't make that connection?

**Comment by sdsykes** [comment]
Closing now, assuming configuration issue of heroku.
